
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.mooncoder.mapleanalyzer.logic.syntax;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int MENOS = 26;
  public static final int IZQ_CORCHETE = 22;
  public static final int EJE_Y = 9;
  public static final int EJE_X = 8;
  public static final int ETIQUETAS = 2;
  public static final int EJECUTAR = 16;
  public static final int DER_CORCHETE = 23;
  public static final int LITERAL = 32;
  public static final int IZQ_LLAVE = 24;
  public static final int POR = 28;
  public static final int TIPO = 11;
  public static final int PORCENTAJE = 13;
  public static final int BARRAS = 4;
  public static final int VALORES = 3;
  public static final int ASIGNAR = 18;
  public static final int COMA = 19;
  public static final int SEPARADOR = 17;
  public static final int NUMBER = 31;
  public static final int EOF = 0;
  public static final int TOTAL = 6;
  public static final int DEF = 15;
  public static final int DIV = 29;
  public static final int PIE = 12;
  public static final int EXTRA = 7;
  public static final int CANTIDAD = 14;
  public static final int error = 1;
  public static final int UNIR = 10;
  public static final int DER_PARENTESIS = 21;
  public static final int TITULO = 5;
  public static final int MAS = 27;
  public static final int DER_LLAVE = 25;
  public static final int NEGADO = 30;
  public static final int IZQ_PARENTESIS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ETIQUETAS",
  "VALORES",
  "BARRAS",
  "TITULO",
  "TOTAL",
  "EXTRA",
  "EJE_X",
  "EJE_Y",
  "UNIR",
  "TIPO",
  "PIE",
  "PORCENTAJE",
  "CANTIDAD",
  "DEF",
  "EJECUTAR",
  "SEPARADOR",
  "ASIGNAR",
  "COMA",
  "IZQ_PARENTESIS",
  "DER_PARENTESIS",
  "IZQ_CORCHETE",
  "DER_CORCHETE",
  "IZQ_LLAVE",
  "DER_LLAVE",
  "MENOS",
  "MAS",
  "POR",
  "DIV",
  "NEGADO",
  "NUMBER",
  "LITERAL"
  };
}

